- hosts: all
  become: true
  tasks:
  - name: "create nodejs repoisitory"
    shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
  - name: "installing node.js"
    yum:
      name: 
        - nodejs
        - gcc-c++
        - make
      state: latest
