---
- hosts: all
  become: yes
  tasks:
  - name: "create nodejs repoisitory"
    shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
  - name: "installing node.js"
    yum:
    - name: 
        - node.js
        - gcc-c++
        - make
      state: latest
